### PR TITLE
Add Rancher projects

### PR DESCRIPTION
**Pull request by knqyf263**
## Description
Add Rancher projects following the discussion in https://github.com/rancher/vexhub/issues/23.

Other namespaces, such as `harvester` and `k3s`, will be added in the subsequent PRs.

## Test
Locally tested

```
Oct 23 23:26:34.027 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/confd
Oct 23 23:26:34.027 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:34.936 INF Parsing VEX file purl=pkg:golang/github.com/rancher/confd url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/confd/scan.openvex.json
Oct 23 23:26:34.947 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/fleet
Oct 23 23:26:34.947 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:35.899 INF Parsing VEX file purl=pkg:golang/github.com/rancher/fleet url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/fleet/scan.openvex.json
Oct 23 23:26:35.907 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/image-build-rke2-cloud-provider
Oct 23 23:26:35.908 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:36.906 INF Parsing VEX file purl=pkg:golang/github.com/rancher/image-build-rke2-cloud-provider url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/image-build-rke2-cloud-provider/scan.openvex.json
Oct 23 23:26:36.915 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/kube-api-auth
Oct 23 23:26:36.915 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:37.865 INF Parsing VEX file purl=pkg:golang/github.com/rancher/kube-api-auth url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/kube-api-auth/scan.openvex.json
Oct 23 23:26:37.875 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/machine
Oct 23 23:26:37.875 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:38.798 INF Parsing VEX file purl=pkg:golang/github.com/rancher/machine url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/machine/scan.openvex.json
Oct 23 23:26:38.806 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/rancher
Oct 23 23:26:38.806 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:39.874 INF Parsing VEX file purl=pkg:golang/github.com/rancher/rancher url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/rancher/scan.openvex.json
Oct 23 23:26:39.887 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/rke2
Oct 23 23:26:39.887 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:40.860 INF Parsing VEX file purl=pkg:golang/github.com/rancher/rke2 url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/rke2/scan.openvex.json
Oct 23 23:26:40.868 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/support-bundle-kit
Oct 23 23:26:40.868 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:41.923 INF Parsing VEX file purl=pkg:golang/github.com/rancher/support-bundle-kit url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/support-bundle-kit/scan.openvex.json
Oct 23 23:26:41.931 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/system-agent
Oct 23 23:26:41.931 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:42.970 INF Parsing VEX file purl=pkg:golang/github.com/rancher/system-agent url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/system-agent/scan.openvex.json
Oct 23 23:26:42.979 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/webhook
Oct 23 23:26:42.979 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:44.021 INF Parsing VEX file purl=pkg:golang/github.com/rancher/webhook url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/webhook/scan.openvex.json
Oct 23 23:26:44.030 INF Crawling package... type=golang purl=pkg:golang/github.com/rancher/wharfie
Oct 23 23:26:44.030 INF Downloading... src="git::https://github.com/rancher/vexhub.git?depth=1&ref=main"
Oct 23 23:26:45.071 INF Parsing VEX file purl=pkg:golang/github.com/rancher/wharfie url=https://github.com/rancher/vexhub path=pkg/golang/github.com/rancher/wharfie/scan.openvex.json
```

## PRs
Blocked by https://github.com/aquasecurity/vexhub-crawler/pull/28

### CODE REVIEW

**Comment by knqyf263** [comment]
@macedogm Could you take a look?

**Comment by macedogm** [comment]
@knqyf263 LGTM! Thank you for submitting this PR 🙇🏻

**Review by DmitriyLewen — APPROVED** [review]
LGTM

**Comment by knqyf263** [comment]
> @knqyf263 LGTM! Thank you for submitting this PR 🙇🏻 

Thanks for your review!

**Comment by knqyf263** [comment]
🎉 
https://github.com/aquasecurity/vexhub/commit/25a6a0337648fe8f82daaff57544edfa2949277c#diff-913d555046f19ff718699008ad87c5fdfbed614d845165451664b06408aeaa64R6

**Pull request merged**
